export const SIGN_UP = 'SIGN_UP';
export const SIGN_IN="SIGN_IN"
export const SIGN_OUT="SIGN_OUT"
export const SIGNUP_ERROR="SIGNUP_ERROR"
export const SIGNIN_ERROR="SIGNIN_ERROR"
export const ADD_NOTE = 'ADD_NOTE';
export const REMOVE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const ADD_SUBNOTE = 'ADD_SUBNOTE';
export const GET_USER = 'GET_USER';
export const FETCH_NOTES = 'FETCH_NOTES';
export const NO_USER = 'NO_USER';
